# Verify External/Internal LB schema against ACP 4.3.2 CRD before apply.
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: BaremetalCluster
metadata:
  name: olvm-workloadcluster
  namespace: cpaas-system
spec:
  controlPlaneLoadBalancer:
    type: External
    host: 10.243.166.12
    port: 6443
