apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: BaremetalMachineTemplate
metadata:
  name: olvm-workloadcluster-worker-machine-template
  namespace: cpaas-system
spec:
  template:
    spec:
      machineInventoryPoolRef:
        name: olvm-workloadcluster-worker-pool
      allocationPolicy: Ordered
